from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
from utils import*
import cv2

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1054, 659)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcd_clock = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_clock.setGeometry(QtCore.QRect(830, 0, 211, 51))
        font = QtGui.QFont()
        font.setFamily("was@peenang")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lcd_clock.setFont(font)
        self.lcd_clock.setMouseTracking(False)
        self.lcd_clock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd_clock.setAutoFillBackground(False)
        self.lcd_clock.setStyleSheet("color: #000000;")
        self.lcd_clock.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_clock.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_clock.setSmallDecimalPoint(True)
        self.lcd_clock.setDigitCount(8)
        self.lcd_clock.setObjectName("lcd_clock")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 391, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.menu = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.menu.setContentsMargins(0, 0, 0, 0)
        self.menu.setObjectName("menu")
        self.cam_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.cam_label.setFont(font)
        self.cam_label.setObjectName("cam_label")
        self.menu.addWidget(self.cam_label)
        self.list_cam = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.list_cam.setObjectName("list_cam")
        self.list_cam.addItem("")
        self.list_cam.setItemText(0, "")
        self.list_cam.addItem("")
        self.list_cam.addItem("")
        self.menu.addWidget(self.list_cam)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.menu.addItem(spacerItem)
        self.Run_Stop = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Run_Stop.setFont(font)
        self.Run_Stop.setObjectName("Run_Stop")
        self.menu.addWidget(self.Run_Stop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.menu.addItem(spacerItem1)
        self.Set = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Set.setFont(font)
        self.Set.setObjectName("Set")
        self.menu.addWidget(self.Set)
        self.main_box = QtWidgets.QGroupBox(self.centralwidget)
        self.main_box.setGeometry(QtCore.QRect(240, 60, 491, 341))
        self.main_box.setFont(font)
        self.main_box.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.main_box.setFlat(False)
        self.main_box.setCheckable(False)
        self.main_box.setObjectName("main_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.main_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.disp_main = QtWidgets.QLabel(self.main_box)
        self.disp_main.setMaximumSize(QtCore.QSize(511, 300))
        self.disp_main.setStyleSheet("background-color: rgb(246, 247, 247);")
        self.disp_main.setAlignment(QtCore.Qt.AlignCenter)
        self.disp_main.setObjectName("disp_main")
        self.gridLayout_3.addWidget(self.disp_main, 0, 0, 1, 1)
        self.Angel_box = QtWidgets.QGroupBox(self.centralwidget)
        self.Angel_box.setGeometry(QtCore.QRect(730, 60, 311, 101))
        self.Angel_box.setFont(font)
        self.Angel_box.setObjectName("Angel_box")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Angel_box)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 50, 181, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.x_y_value = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.x_y_value.setContentsMargins(0, 0, 0, 0)
        self.x_y_value.setObjectName("x_y_value")
        self.x = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.x.setFont(font)
        self.x.setObjectName("x")
        self.x_y_value.addWidget(self.x)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.x_y_value.addItem(spacerItem2)
        self.x_value = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.x_value.setFont(font)
        self.x_value.setObjectName("x_value")
        self.x_y_value.addWidget(self.x_value)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.x_y_value.addItem(spacerItem3)
        self.y = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.y.setFont(font)
        self.y.setObjectName("y")
        self.x_y_value.addWidget(self.y)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.x_y_value.addItem(spacerItem4)
        self.y_value = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.y_value.setFont(font)
        self.y_value.setObjectName("y_value")
        self.x_y_value.addWidget(self.y_value)
        self.angle = QtWidgets.QLabel(self.Angel_box)
        self.angle.setGeometry(QtCore.QRect(130, 20, 51, 20))
        self.angle.setObjectName("angle")
        self.Information_box = QtWidgets.QGroupBox(self.centralwidget)
        self.Information_box.setGeometry(QtCore.QRect(730, 160, 311, 431))
        self.Information_box.setFont(font)
        self.Information_box.setObjectName("Information_box")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Information_box)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 141, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ID = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ID.setFont(font)
        self.ID.setObjectName("ID")
        self.verticalLayout.addWidget(self.ID)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.color = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.color.setFont(font)
        self.color.setObjectName("color")
        self.verticalLayout.addWidget(self.color)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.address = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.address.setFont(font)
        self.address.setObjectName("address")
        self.verticalLayout.addWidget(self.address)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.type = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.type.setFont(font)
        self.type.setObjectName("type")
        self.verticalLayout.addWidget(self.type)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.price = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.price.setFont(font)
        self.price.setObjectName("price")
        self.verticalLayout.addWidget(self.price)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Information_box)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(160, 20, 141, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ID_value = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ID_value.setFont(font)
        self.ID_value.setObjectName("ID_value")
        self.verticalLayout_2.addWidget(self.ID_value)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.color_value = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.color_value.setFont(font)
        self.color_value.setObjectName("color_value")
        self.verticalLayout_2.addWidget(self.color_value)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.address_value = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.address_value.setFont(font)
        self.address_value.setObjectName("address_value")
        self.verticalLayout_2.addWidget(self.address_value)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem11)
        self.type_value = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.type_value.setFont(font)
        self.type_value.setObjectName("type_value")
        self.verticalLayout_2.addWidget(self.type_value)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.price_value = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.price_value.setFont(font)
        self.price_value.setObjectName("price_value")
        self.verticalLayout_2.addWidget(self.price_value)
        self.log_box = QtWidgets.QGroupBox(self.centralwidget)
        self.log_box.setGeometry(QtCore.QRect(240, 400, 491, 221))
        self.log_box.setFont(font)
        self.log_box.setObjectName("log_box")
        self.history = QtWidgets.QTextEdit(self.log_box)
        self.history.setGeometry(QtCore.QRect(10, 20, 471, 191))
        self.history.setStyleSheet("background-color: rgb(246, 247, 247);\n"
"border-radius:3px;")
        self.history.setReadOnly(True)
        self.history.setObjectName("history")
        self.close = QtWidgets.QPushButton(self.centralwidget)
        self.close.setGeometry(QtCore.QRect(970, 600, 71, 31))
        self.close.setFont(font)
        self.close.setObjectName("close")
        self.Performance_box = QtWidgets.QGroupBox(self.centralwidget)
        self.Performance_box.setGeometry(QtCore.QRect(10, 60, 231, 301))
        self.Performance_box.setFont(font)
        self.Performance_box.setObjectName("Performance_box")
        self.counter = QtWidgets.QGroupBox(self.Performance_box)
        self.counter.setGeometry(QtCore.QRect(0, 40, 231, 101))
        self.counter.setObjectName("counter")
        self.splitter_11 = QtWidgets.QSplitter(self.counter)
        self.splitter_11.setGeometry(QtCore.QRect(10, 50, 221, 41))
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName("splitter_11")
        self.lcd_obj1 = QtWidgets.QLCDNumber(self.splitter_11)
        self.lcd_obj1.setObjectName("lcd_obj1")
        self.lcd_obj2 = QtWidgets.QLCDNumber(self.splitter_11)
        self.lcd_obj2.setObjectName("lcd_obj2")
        self.splitter_12 = QtWidgets.QSplitter(self.counter)
        self.splitter_12.setGeometry(QtCore.QRect(10, 25, 221, 20))
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName("splitter_12")
        self.obj1 = QtWidgets.QLabel(self.splitter_12)
        self.obj1.setAlignment(QtCore.Qt.AlignCenter)
        self.obj1.setObjectName("obj1")
        self.obj2 = QtWidgets.QLabel(self.splitter_12)
        self.obj2.setAlignment(QtCore.Qt.AlignCenter)
        self.obj2.setObjectName("obj2")
        self.runtime = QtWidgets.QGroupBox(self.Performance_box)
        self.runtime.setGeometry(QtCore.QRect(0, 140, 231, 101))
        self.runtime.setObjectName("runtime")
        self.lcd_clock_2 = QtWidgets.QLCDNumber(self.runtime)
        self.lcd_clock_2.setGeometry(QtCore.QRect(10, 40, 211, 51))
        self.lcd_clock_2.setFont(font)
        self.lcd_clock_2.setMouseTracking(False)
        self.lcd_clock_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd_clock_2.setAutoFillBackground(False)
        self.lcd_clock_2.setStyleSheet("color: #000000;")
        self.lcd_clock_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_clock_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_clock_2.setSmallDecimalPoint(True)
        self.lcd_clock_2.setDigitCount(8)
        self.lcd_clock_2.setObjectName("lcd_clock_2")
        self.QR_box = QtWidgets.QGroupBox(self.centralwidget)
        self.QR_box.setGeometry(QtCore.QRect(10, 360, 231, 231))
        self.QR_box.setFont(font)
        self.QR_box.setObjectName("QR_box")
        self.disp_qr = QtWidgets.QLabel(self.QR_box)
        self.disp_qr.setGeometry(QtCore.QRect(10, 20, 211, 201))
        self.disp_qr.setMaximumSize(QtCore.QSize(511, 300))
        self.disp_qr.setStyleSheet("background-color: rgb(246, 247, 247);")
        self.disp_qr.setAlignment(QtCore.Qt.AlignCenter)
        self.disp_qr.setObjectName("disp_qr")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.cap = None

        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(lambda: showTime(self.lcd_clock))
        self.timer.timeout.connect(self.update_frame)
        self.timer.start(1000)

        self.close.clicked.connect(lambda: close_software(MainWindow))
        self.Run_Stop.clicked.connect(self.toggle_streaming)

    def toggle_streaming(self):
        if self.cap is None:
            self.cap = cv2.VideoCapture(0)  # Thay đổi `0` thành ID camera của bạn nếu cần
            self.timer.start(30)  # Cập nhật mỗi 30ms
            self.Run_Stop.setText("STOP")
            self.Run_Stop.setStyleSheet("background-color: red; color: white;")
        else:
            self.timer.stop()
            self.cap.release()
            self.cap = None
            self.Run_Stop.setText("RUN")
            self.Run_Stop.setStyleSheet("background-color: green; color: white;")
            self.disp_main.clear()  # Xóa hình ảnh hiện tại

    def update_frame(self):
        if self.cap is not None:
            ret, frame = self.cap.read()
            if ret:
                # Chuyển đổi từ BGR (OpenCV) sang RGB (Qt)
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                h, w, ch = frame.shape
                bytes_per_line = ch * w
                q_img = QImage(frame.data, w, h, bytes_per_line, QImage.Format_RGB888)
                self.disp_main.setPixmap(QPixmap.fromImage(q_img))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cam_label.setText(_translate("MainWindow", "Camera"))
        self.list_cam.setItemText(1, _translate("MainWindow", "IMX219"))
        self.list_cam.setItemText(2, _translate("MainWindow", "Webcam"))
        self.Run_Stop.setText(_translate("MainWindow", "RUN"))
        self.Set.setText(_translate("MainWindow", "RESET"))
        self.main_box.setTitle(_translate("MainWindow", "Main"))
        self.disp_main.setText(_translate("MainWindow", "Main Source"))
        self.Angel_box.setTitle(_translate("MainWindow", "Angle"))
        self.x.setText(_translate("MainWindow", "X"))
        self.x_value.setText(_translate("MainWindow", "0.0"))
        self.y.setText(_translate("MainWindow", "Y"))
        self.y_value.setText(_translate("MainWindow", "0.0"))
        self.angle.setText(_translate("MainWindow", "0.0"))
        self.Information_box.setTitle(_translate("MainWindow", "Information"))
        self.ID.setText(_translate("MainWindow", "ID"))
        self.color.setText(_translate("MainWindow", "Color"))
        self.address.setText(_translate("MainWindow", "Address"))
        self.type.setText(_translate("MainWindow", "Type"))
        self.price.setText(_translate("MainWindow", "Price"))
        self.ID_value.setText(_translate("MainWindow", "0"))
        self.color_value.setText(_translate("MainWindow", "White"))
        self.address_value.setText(_translate("MainWindow", "Address"))
        self.type_value.setText(_translate("MainWindow", "Goods"))
        self.price_value.setText(_translate("MainWindow", "VND"))
        self.log_box.setTitle(_translate("MainWindow", "Log"))
        self.close.setText(_translate("MainWindow", "Close"))
        self.Performance_box.setTitle(_translate("MainWindow", "Performance"))
        self.counter.setTitle(_translate("MainWindow", "Counter"))
        self.obj1.setText(_translate("MainWindow", "Object 1"))
        self.obj2.setText(_translate("MainWindow", "Object 2"))
        self.runtime.setTitle(_translate("MainWindow", "Runtime"))
        self.QR_box.setTitle(_translate("MainWindow", "QR Code"))
        self.disp_qr.setText(_translate("MainWindow", "QR Source"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())